### ISSUE TITLE
Utility functions: handle nulls and Strings gracefully

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-transformations#21]
In order to ease the usage of the standard function we should handle nulls in a way that prevents NPE.

For instance:
```
uppercase(null)-> null
lowercase(null) -> null
contains(?, null) -> false
contains(null,?) -> false
trim(null) -> null
```
Also all those functions should take "Object" as parameter and cast it to String (by calling toString)

an alternative is to return the empty String, but users can use "coalesce" (or whenNull as noted below)

we should also provide something to safely concatenate fields
```
trim(Object) -> usual String.trim() method
concat(Object a, Object b) -> concatenates 2 strings, and null is considered a "empty" String
```

Thinking more to `coalesce`, it is a SQL term, I have always used it, but maybe we can name it like "whenNull" or something like that
```
whenNotNull(field/expression, value)
whenNull(field, defaultValue) 
```

`fullname = fn:contact(value.firstname, whenNotNull(field.surname, fn:contact(" ", field.surname))`

**Comment by aymkhalil** [comment]
> Also all those functions should take "Object" as parameter and cast it to String (by calling toString)

I'm not sure about the toString part. It makes sense for functions like printing or logging, but what is the use case of a user passing a non-string object and wanting to uppercase it?

**Comment by aymkhalil** [comment]
I think `coalesce ` is more clearer to the use about expectation (SQL is familiar, but also the operation itself is not SQL specific, check C#'s [coalescing assignment](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/null-coalescing-assignment)).

Also `whenNotNull(field/expression, value)` is not clear about what is the behavior if null (does it return null or field/expression). Similarity, `whenNull(field, defaultValue) ` is not explicit about about what happens if not null..

Btw the ternary operator is supported, so user can always say smth like `value == null ? 'x' : 'y or value or whatever'`

**Comment by aymkhalil** [comment]
On the second though, String.valueOf does actually what you are proposing about .toString. It seems it will minimize any chance of errors rather than the actual evaluation is useful so we minimize errors at evaluation time, I included it in the PR
